trigger:
- master
- stable/*

pr:
- master
- stable/*

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'VS2022'
    vm_image: 'windows-2022'
    arch_list: "IA32,X64"
